In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix

In [2]:
data = pd.read_csv('sonar_data.csv', header = None)
data.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [3]:
data.shape

(208, 61)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       208 non-null    float64
 1   1       208 non-null    float64
 2   2       208 non-null    float64
 3   3       208 non-null    float64
 4   4       208 non-null    float64
 5   5       208 non-null    float64
 6   6       208 non-null    float64
 7   7       208 non-null    float64
 8   8       208 non-null    float64
 9   9       208 non-null    float64
 10  10      208 non-null    float64
 11  11      208 non-null    float64
 12  12      208 non-null    float64
 13  13      208 non-null    float64
 14  14      208 non-null    float64
 15  15      208 non-null    float64
 16  16      208 non-null    float64
 17  17      208 non-null    float64
 18  18      208 non-null    float64
 19  19      208 non-null    float64
 20  20      208 non-null    float64
 21  21      208 non-null    float64
 22  22

In [5]:
data.describe()

0           1           2           3           4           5   \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.029164    0.038437    0.043832    0.053892    0.075202    0.104570   
std      0.022991    0.032960    0.038428    0.046528    0.055552    0.059105   
min      0.001500    0.000600    0.001500    0.005800    0.006700    0.010200   
25%      0.013350    0.016450    0.018950    0.024375    0.038050    0.067025   
50%      0.022800    0.030800    0.034300    0.044050    0.062500    0.092150   
75%      0.035550    0.047950    0.057950    0.064500    0.100275    0.134125   
max      0.137100    0.233900    0.305900    0.426400    0.401000    0.382300   

               6           7           8           9   ...          50  \
count  208.000000  208.000000  208.000000  208.000000  ...  208.000000   
mean     0.121747    0.134799    0.178003    0.208259  ...    0.016069   
std      0.061788    0.085152    0.118387    0.134416  ...    0.012008   
min      0.003300    0.005500    0.007500    0.011300  ...    0.000000   
25%      0.080900    0.080425    0.097025    0.111275  ...    0.008425   
50%      0.106950    0.112100    0.152250    0.182400  ...    0.013900   
75%      0.154000    0.169600    0.233425    0.268700  ...    0.020825   
max      0.372900    0.459000    0.682800    0.710600  ...    0.100400   

               51          52          53          54          55          56  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.013420    0.010709    0.010941    0.009290    0.008222    0.007820   
std      0.009634    0.007060    0.007301    0.007088    0.005736    0.005785   
min      0.000800    0.000500    0.001000    0.000600    0.000400    0.000300   
25%      0.007275    0.005075    0.005375    0.004150    0.004400    0.003700   
50%      0.011400    0.009550    0.009300    0.007500    0.006850    0.005950   
75%      0.016725    0.014900    0.014500    0.012100    0.010575    0.010425   
max      0.070900    0.039000    0.035200    0.044700    0.039400    0.035500   

               57          58          59  
count  208.000000  208.000000  208.000000  
mean     0.007949    0.007941    0.006507  
std      0.006470    0.006181    0.005031  
min      0.000300    0.000100    0.000600  
25%      0.003600    0.003675    0.003100  
50%      0.005800    0.006400    0.005300  
75%      0.010350    0.010325    0.008525  
max      0.044000    0.036400    0.043900  

[8 rows x 60 columns]

In [6]:
data.columns

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60],
      dtype='int64')

In [7]:
data[60].nunique()

2

In [8]:
data[60].value_counts()

60
M    111
R     97
Name: count, dtype: int64

In [9]:
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [10]:
x

array([[0.02  , 0.0371, 0.0428, ..., 0.0084, 0.009 , 0.0032],
       [0.0453, 0.0523, 0.0843, ..., 0.0049, 0.0052, 0.0044],
       [0.0262, 0.0582, 0.1099, ..., 0.0164, 0.0095, 0.0078],
       ...,
       [0.0522, 0.0437, 0.018 , ..., 0.0138, 0.0077, 0.0031],
       [0.0303, 0.0353, 0.049 , ..., 0.0079, 0.0036, 0.0048],
       [0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115]])

In [11]:
y

array(['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M

In [12]:
data.groupby(60).mean()

0         1         2         3         4         5         6   \
60                                                                         
M   0.034989  0.045544  0.050720  0.064768  0.086715  0.111864  0.128359   
R   0.022498  0.030303  0.035951  0.041447  0.062028  0.096224  0.114180   

          7         8         9   ...        50        51        52        53  \
60                                ...                                           
M   0.149832  0.213492  0.251022  ...  0.019352  0.016014  0.011643  0.012185   
R   0.117596  0.137392  0.159325  ...  0.012311  0.010453  0.009640  0.009518   

          54        55        56        57        58        59  
60                                                              
M   0.009923  0.008914  0.007825  0.009060  0.008695  0.006930  
R   0.008567  0.007430  0.007814  0.006677  0.007078  0.006024  

[2 rows x 60 columns]

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, stratify = y, random_state = 42)
print(x_train)

[[0.0491 0.0279 0.0592 ... 0.014  0.0332 0.0439]
 [0.0968 0.0821 0.0629 ... 0.0201 0.021  0.0041]
 [0.0335 0.0258 0.0398 ... 0.0022 0.0005 0.0031]
 ...
 [0.0856 0.0454 0.0382 ... 0.0102 0.0037 0.0037]
 [0.0231 0.0351 0.003  ... 0.0038 0.0043 0.003 ]
 [0.0216 0.0215 0.0273 ... 0.0024 0.0009 0.0017]]


In [14]:
x_train

array([[0.0491, 0.0279, 0.0592, ..., 0.014 , 0.0332, 0.0439],
       [0.0968, 0.0821, 0.0629, ..., 0.0201, 0.021 , 0.0041],
       [0.0335, 0.0258, 0.0398, ..., 0.0022, 0.0005, 0.0031],
       ...,
       [0.0856, 0.0454, 0.0382, ..., 0.0102, 0.0037, 0.0037],
       [0.0231, 0.0351, 0.003 , ..., 0.0038, 0.0043, 0.003 ],
       [0.0216, 0.0215, 0.0273, ..., 0.0024, 0.0009, 0.0017]])

In [15]:
x_test

array([[0.0181, 0.0146, 0.0026, ..., 0.0048, 0.0089, 0.0085],
       [0.0099, 0.0484, 0.0299, ..., 0.016 , 0.0106, 0.0134],
       [0.0317, 0.0956, 0.1321, ..., 0.0143, 0.0036, 0.0103],
       ...,
       [0.1083, 0.107 , 0.0257, ..., 0.0122, 0.0082, 0.0143],
       [0.0158, 0.0239, 0.015 , ..., 0.0046, 0.0022, 0.0021],
       [0.0036, 0.0078, 0.0092, ..., 0.0049, 0.0024, 0.0016]])

In [16]:
y_train

array(['M', 'M', 'M', 'R', 'M', 'R', 'M', 'M', 'R', 'R', 'M', 'M', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'M', 'M', 'M', 'R', 'M',
       'R', 'M', 'M', 'M', 'R', 'M', 'R', 'R', 'R', 'M', 'M', 'R', 'R',
       'R', 'M', 'M', 'M', 'R', 'R', 'R', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'R', 'M', 'R', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'R', 'R', 'M', 'R', 'M', 'M', 'M', 'M', 'R', 'M',
       'M', 'M', 'R', 'M', 'R', 'R', 'M', 'M', 'R', 'R', 'R', 'M', 'M',
       'R', 'M', 'R', 'M', 'R', 'M', 'R', 'M', 'R', 'M', 'R', 'M', 'R',
       'R', 'M', 'M', 'M', 'R', 'M', 'M', 'R', 'M', 'R', 'M', 'R', 'M',
       'R', 'R', 'M', 'R', 'M', 'M', 'R', 'M', 'R', 'M', 'M', 'M', 'R',
       'M', 'R', 'R', 'M', 'R', 'M', 'M', 'R', 'R', 'M', 'M', 'R', 'M',
       'R', 'R', 'M', 'R', 'M', 'R', 'R', 'R', 'R', 'R', 'R', 'M', 'M',
       'M', 'R', 'R', 'M', 'R', 'R', 'M', 'R', 'R', 'R'], dtype=object)

In [17]:
y_test

array(['R', 'R', 'R', 'M', 'M', 'M', 'M', 'R', 'M', 'M', 'R', 'M', 'R',
       'R', 'R', 'R', 'M', 'M', 'R', 'M', 'M', 'R', 'M', 'R', 'R', 'R',
       'R', 'M', 'M', 'R', 'R', 'M', 'R', 'M', 'R', 'M', 'M', 'M', 'M',
       'M', 'M', 'R'], dtype=object)

In [18]:
sc = StandardScaler()
regressor = LogisticRegression()
regressor.fit(x_train,y_train)

LogisticRegression()

In [19]:
y_pred = regressor.predict(x_test)

In [20]:
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[['R' 'R']
 ['M' 'R']
 ['R' 'R']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['R' 'M']
 ['R' 'R']
 ['M' 'M']
 ['R' 'R']
 ['R' 'R']
 ['R' 'R']
 ['R' 'R']
 ['M' 'M']
 ['M' 'M']
 ['M' 'R']
 ['M' 'M']
 ['M' 'M']
 ['M' 'R']
 ['M' 'M']
 ['R' 'R']
 ['R' 'R']
 ['R' 'R']
 ['R' 'R']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'R']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['M' 'R']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']]


In [21]:
cm = confusion_matrix(y_pred,y_test)
print(cm)

[[21  5]
 [ 1 15]]


In [22]:
print(accuracy_score(y_test,y_pred))

0.8571428571428571


In [23]:
result = regressor.predict(sc.fit_transform([[0.0336	,0.0294	,0.0476	,0.0539	,0.0194	,0.0804	,0.1136,	0.1228	,0.1235,	0.0842,	0.0357,	0.0689,	0.1705	,0.3257	,0.4602,	0.6225	,0.7327,	0.7843,	0.7988,	0.8261,	1,	0.9814,	0.962	,0.9601	,0.9118	,0.9086	,0.7931,	0.5877,	0.3474,	0.4235	,0.4633,	0.341,	0.2849,	0.2847	,0.1742	,0.0549,	0.1192	,0.1154,	0.0855	,0.1811,	0.1264	,0.0799,	0.0378,	0.1268	,0.1125	,0.0505	,0.0949,	0.0677,	0.0259	,0.017,	0.0033,	0.015	,0.0111,	0.0032	,0.0035	,0.0169	,0.0137	,0.0015,	0.0069	,0.0051
]]))
if(result == 'R'):
    print('The object is a Rock')
else:
    print('the object is a mine')

The object is a Rock


In [24]:
# Our model's prediction accuracy is over 85% :-)